In [2]:
import pandas as pd

In [ ]:
pd.read_csv("/data/uni/crypto/clean/okex-swap_1000/clean_orderbook_bps/2025-09-07/BTC-USDT-SWAP.csv.gz").tail(20)

,Unnamed: 0,start,volume,turnover,open,close,high,low,open_interest,num,vwap,buy_volume,sell_volume,buy_num,sell_num,buy_vwap,sell_vwap,symbol
86380,86380,1757289580000,2.62,2.910886e+05,111102.5,111102.6,111102.6,111102.5,2639266.57,8.0,111102.500382,0.01,2.61,1.0,7.0,111102.6,111102.500000,BTC-USDT-SWAP
86381,86381,1757289581000,0.00,0.000000e+00,111102.6,111102.6,111102.6,111102.6,2639266.57,0.0,NaN,0.00,0.00,0.0,0.0,NaN,NaN,BTC-USDT-SWAP
86382,86382,1757289582000,11.97,1.329897e+06,111102.5,111102.5,111102.5,111102.5,2639266.57,6.0,111102.500000,0.00,11.97,0.0,6.0,NaN,111102.500000,BTC-USDT-SWAP
86383,86383,1757289583000,0.01,1.111025e+03,111102.5,111102.5,111102.5,111102.5,2639266.57,1.0,111102.500000,0.00,0.01,0.0,1.0,NaN,111102.500000,BTC-USDT-SWAP
86384,86384,1757289584000,4.89,5.432913e+05,111102.5,111102.5,111102.6,111102.5,2639270.66,7.0,111102.506544,0.32,4.57,1.0,6.0,111102.6,111102.500000,BTC-USDT-SWAP
86385,86385,1757289585000,181.50,2.016510e+07,111102.5,111102.5,111102.5,111102.5,2639270.66,7.0,111102.500000,0.00,181.50,0.0,7.0,NaN,111102.500000,BTC-USDT-SWAP
86386,86386,1757289586000,408.66,4.540119e+07,111102.5,111085.5,111102.5,111085.5,2639270.66,126.0,111097.713992,0.00,408.66,0.0,126.0,NaN,111097.713992,BTC-USDT-SWAP
86387,86387,1757289587000,153.19,1.701704e+07,111085.5,111081.4,111085.5,111081.4,2639270.66,29.0,111084.507030,35.09,118.10,5.0,24.0,111081.4,111085.430195,BTC-USDT-SWAP
86388,86388,1757289588000,1.22,1.355192e+05,111081.3,111081.3,111081.3,111081.3,2639217.09,6.0,111081.300000,0.00,1.22,0.0,6.0,NaN,111081.300000,BTC-USDT-SWAP
86389,86389,1757289589000,0.00,0.000000e+00,111081.3,111081.3,111081.3,111081.3,2639217.09,0.0,NaN,0.00,0.00,0.0,0.0,NaN,NaN,BTC-USDT-SWAP
86390,86390,1757289590000,1.21,1.344084e+05,111081.3,111081.3,111081.3,111081.3,2639217.09,5.0,111081.300000,0.00,1.21,0.0,5.0,NaN,111081.300000,BTC-USDT-SWAP
86391,86391,1757289591000,3.22,3.576819e+05,111081.3,111081.3,111081.4,111081.3,2639217.09,3.0,111081.346584,1.50,1.72,1.0,2.0,111081.4,111081.300000,BTC-USDT-SWAP
86392,86392,1757289592000,1.25,1.388516e+05,111081.3,111081.3,111081.3,111081.3,2639101.49,6.0,111081.300000,0.00,1.25,0.0,6.0,NaN,111081.300000,BTC-USDT-SWAP
86393,86393,1757289593000,0.36,3.998927e+04,111081.3,111081.3,111081.3,111081.3,2639101.49,1.0,111081.300000,0.00,0.36,0.0,1.0,NaN,111081.300000,BTC-USDT-SWAP
86394,86394,1757289594000,0.84,9.330829e+04,111081.3,111081.3,111081.3,111081.3,2639101.49,4.0,111081.300000,0.00,0.84,0.0,4.0,NaN,111081.300000,BTC-USDT-SWAP
86395,86395,1757289595000,2.15,2.388248e+05,111081.3,111081.3,111081.3,111081.3,2639101.49,2.0,111081.300000,0.00,2.15,0.0,2.0,NaN,111081.300000,BTC-USDT-SWAP
86396,86396,1757289596000,22.28,2.474892e+06,111081.3,111081.3,111081.4,111081.3,2639103.55,6.0,111081.342729,9.52,12.76,1.0,5.0,111081.4,111081.300000,BTC-USDT-SWAP
86397,86397,1757289597000,0.00,0.000000e+00,111081.3,111081.3,111081.3,111081.3,2639103.55,0.0,NaN,0.00,0.00,0.0,0.0,NaN,NaN,BTC-USDT-SWAP
86398,86398,1757289598000,4.35,4.832040e+05,111081.3,111081.3,111081.4,111081.3,2639103.55,7.0,111081.371034,3.09,1.26,1.0,6.0,111081.4,111081.300000,BTC-USDT-SWAP
86399,86399,1757289599000,16.84,1.870601e+06,111081.3,111079.0,111081.3,111079.0,2639103.55,16.0,111080.794359,0.00,16.84,0.0,16.0,NaN,111080.794359,BTC-USDT-SWAP

In [4]:
import polars as pl
pl.read_parquet("/data/uni/crypto/parquet_tardis/binance-futures/incremental_book_L2/2025-09-10/CRVUSDT.parquet")

shape: (4_206_736, 6)
┌──────────────────┬──────────────────┬─────────────┬──────┬───────┬──────────┐
│ timestamp        ┆ local_timestamp  ┆ is_snapshot ┆ side ┆ price ┆ amount   │
│ ---              ┆ ---              ┆ ---         ┆ ---  ┆ ---   ┆ ---      │
│ i64              ┆ i64              ┆ i8          ┆ i64  ┆ f64   ┆ f64      │
╞══════════════════╪══════════════════╪═════════════╪══════╪═══════╪══════════╡
│ 1757462400485000 ┆ 1757462401053487 ┆ 1           ┆ 2    ┆ 0.778 ┆ 110333.1 │
│ 1757462400485000 ┆ 1757462401053487 ┆ 1           ┆ 2    ┆ 0.779 ┆ 216098.8 │
│ 1757462400485000 ┆ 1757462401053487 ┆ 1           ┆ 2    ┆ 0.78  ┆ 206361.4 │
│ 1757462400485000 ┆ 1757462401053487 ┆ 1           ┆ 2    ┆ 0.781 ┆ 171882.6 │
│ 1757462400485000 ┆ 1757462401053487 ┆ 1           ┆ 2    ┆ 0.782 ┆ 163776.2 │
│ …                ┆ …                ┆ …           ┆ …    ┆ …     ┆ …        │
│ 1757548799845000 ┆ 1757548799847581 ┆ 0           ┆ 2    ┆ 0.794 ┆ 125562.8 │
│ 1757548799845000 ┆ 1757548799847581 ┆ 0           ┆ 1    ┆ 0.77  ┆ 379175.0 │
│ 1757548799943000 ┆ 1757548799944519 ┆ 0           ┆ 2    ┆ 0.782 ┆ 172115.7 │
│ 1757548799943000 ┆ 1757548799944519 ┆ 0           ┆ 2    ┆ 0.79  ┆ 167486.4 │
│ 1757548799943000 ┆ 1757548799944519 ┆ 0           ┆ 1    ┆ 0.742 ┆ 307504.8 │
└──────────────────┴──────────────────┴─────────────┴──────┴───────┴──────────┘