In [1]:
import pandas as pd

In [2]:
pd.read_csv("/data/uni/crypto/clean/okex-swap_1000/clean_basedata/2025-09-07/BTC-USDT-SWAP.csv.gz").tail(20)

,Unnamed: 0,start,volume,turnover,open,close,high,low,open_interest,num,vwap,buy_volume,sell_volume,buy_num,sell_num,buy_vwap,sell_vwap,symbol
86380,86380,1757289580000,2.62,2.910886e+05,111102.5,111102.6,111102.6,111102.5,2639266.57,8.0,111102.500382,0.01,2.61,1.0,7.0,111102.6,111102.500000,BTC-USDT-SWAP
86381,86381,1757289581000,0.00,0.000000e+00,111102.6,111102.6,111102.6,111102.6,2639266.57,0.0,NaN,0.00,0.00,0.0,0.0,NaN,NaN,BTC-USDT-SWAP
86382,86382,1757289582000,11.97,1.329897e+06,111102.5,111102.5,111102.5,111102.5,2639266.57,6.0,111102.500000,0.00,11.97,0.0,6.0,NaN,111102.500000,BTC-USDT-SWAP
86383,86383,1757289583000,0.01,1.111025e+03,111102.5,111102.5,111102.5,111102.5,2639266.57,1.0,111102.500000,0.00,0.01,0.0,1.0,NaN,111102.500000,BTC-USDT-SWAP
86384,86384,1757289584000,4.89,5.432913e+05,111102.5,111102.5,111102.6,111102.5,2639270.66,7.0,111102.506544,0.32,4.57,1.0,6.0,111102.6,111102.500000,BTC-USDT-SWAP
86385,86385,1757289585000,181.50,2.016510e+07,111102.5,111102.5,111102.5,111102.5,2639270.66,7.0,111102.500000,0.00,181.50,0.0,7.0,NaN,111102.500000,BTC-USDT-SWAP
86386,86386,1757289586000,408.66,4.540119e+07,111102.5,111085.5,111102.5,111085.5,2639270.66,126.0,111097.713992,0.00,408.66,0.0,126.0,NaN,111097.713992,BTC-USDT-SWAP
86387,86387,1757289587000,153.19,1.701704e+07,111085.5,111081.4,111085.5,111081.4,2639270.66,29.0,111084.507030,35.09,118.10,5.0,24.0,111081.4,111085.430195,BTC-USDT-SWAP
86388,86388,1757289588000,1.22,1.355192e+05,111081.3,111081.3,111081.3,111081.3,2639217.09,6.0,111081.300000,0.00,1.22,0.0,6.0,NaN,111081.300000,BTC-USDT-SWAP
86389,86389,1757289589000,0.00,0.000000e+00,111081.3,111081.3,111081.3,111081.3,2639217.09,0.0,NaN,0.00,0.00,0.0,0.0,NaN,NaN,BTC-USDT-SWAP
86390,86390,1757289590000,1.21,1.344084e+05,111081.3,111081.3,111081.3,111081.3,2639217.09,5.0,111081.300000,0.00,1.21,0.0,5.0,NaN,111081.300000,BTC-USDT-SWAP
86391,86391,1757289591000,3.22,3.576819e+05,111081.3,111081.3,111081.4,111081.3,2639217.09,3.0,111081.346584,1.50,1.72,1.0,2.0,111081.4,111081.300000,BTC-USDT-SWAP
86392,86392,1757289592000,1.25,1.388516e+05,111081.3,111081.3,111081.3,111081.3,2639101.49,6.0,111081.300000,0.00,1.25,0.0,6.0,NaN,111081.300000,BTC-USDT-SWAP
86393,86393,1757289593000,0.36,3.998927e+04,111081.3,111081.3,111081.3,111081.3,2639101.49,1.0,111081.300000,0.00,0.36,0.0,1.0,NaN,111081.300000,BTC-USDT-SWAP
86394,86394,1757289594000,0.84,9.330829e+04,111081.3,111081.3,111081.3,111081.3,2639101.49,4.0,111081.300000,0.00,0.84,0.0,4.0,NaN,111081.300000,BTC-USDT-SWAP
86395,86395,1757289595000,2.15,2.388248e+05,111081.3,111081.3,111081.3,111081.3,2639101.49,2.0,111081.300000,0.00,2.15,0.0,2.0,NaN,111081.300000,BTC-USDT-SWAP
86396,86396,1757289596000,22.28,2.474892e+06,111081.3,111081.3,111081.4,111081.3,2639103.55,6.0,111081.342729,9.52,12.76,1.0,5.0,111081.4,111081.300000,BTC-USDT-SWAP
86397,86397,1757289597000,0.00,0.000000e+00,111081.3,111081.3,111081.3,111081.3,2639103.55,0.0,NaN,0.00,0.00,0.0,0.0,NaN,NaN,BTC-USDT-SWAP
86398,86398,1757289598000,4.35,4.832040e+05,111081.3,111081.3,111081.4,111081.3,2639103.55,7.0,111081.371034,3.09,1.26,1.0,6.0,111081.4,111081.300000,BTC-USDT-SWAP
86399,86399,1757289599000,16.84,1.870601e+06,111081.3,111079.0,111081.3,111079.0,2639103.55,16.0,111080.794359,0.00,16.84,0.0,16.0,NaN,111080.794359,BTC-USDT-SWAP

In [69]:
import polars as pl
pl.read_parquet("/data/uni/crypto/parquet_tardis/binance-futures/trades/2025-02-01/SOLUSDT.parquet")

shape: (1_501_305, 6)
┌──────────────────┬──────────────────┬────────────┬──────┬────────┬────────┐
│ timestamp        ┆ local_timestamp  ┆ id         ┆ side ┆ price  ┆ amount │
│ ---              ┆ ---              ┆ ---        ┆ ---  ┆ ---    ┆ ---    │
│ i64              ┆ i64              ┆ i64        ┆ i64  ┆ f64    ┆ i64    │
╞══════════════════╪══════════════════╪════════════╪══════╪════════╪════════╡
│ 1738368005365000 ┆ 1738368005367769 ┆ 2063801953 ┆ 1    ┆ 231.6  ┆ 2      │
│ 1738368005378000 ┆ 1738368005381767 ┆ 2063801954 ┆ 1    ┆ 231.6  ┆ 1      │
│ 1738368005404000 ┆ 1738368005407423 ┆ 2063801955 ┆ 1    ┆ 231.6  ┆ 1      │
│ 1738368005480000 ┆ 1738368005483762 ┆ 2063801956 ┆ 2    ┆ 231.59 ┆ 1      │
│ 1738368005480000 ┆ 1738368005483772 ┆ 2063801957 ┆ 2    ┆ 231.59 ┆ 10     │
│ …                ┆ …                ┆ …          ┆ …    ┆ …      ┆ …      │
│ 1738454399912000 ┆ 1738454399915013 ┆ 2065303631 ┆ 2    ┆ 212.88 ┆ 1      │
│ 1738454399912000 ┆ 1738454399915015 ┆ 2065303632 ┆ 2    ┆ 212.88 ┆ 1      │
│ 1738454399912000 ┆ 1738454399915030 ┆ 2065303633 ┆ 2    ┆ 212.88 ┆ 13     │
│ 1738454399912000 ┆ 1738454399915031 ┆ 2065303634 ┆ 2    ┆ 212.88 ┆ 4      │
│ 1738454399945000 ┆ 1738454399947644 ┆ 2065303635 ┆ 1    ┆ 212.89 ┆ 2      │
└──────────────────┴──────────────────┴────────────┴──────┴────────┴────────┘

In [5]:
pd.read_csv("/home/wtr2/statmm/out/SOLUSDT0.csv").head(20)

,timestamp,balance,position,fee,trading_volume,trading_value,num_trades,price
0,1738368001052000000,0,0,0,0,0,0,NaN
1,1738368002052000000,0,0,0,0,0,0,NaN
2,1738368003052000000,0,0,0,0,0,0,NaN
3,1738368004052000000,0,0,0,0,0,0,NaN
4,1738368005052000000,0,0,0,0,0,0,NaN
5,1738368006052000000,0,0,0,0,0,0,NaN
6,1738368007052000000,0,0,0,0,0,0,NaN
7,1738368008052000000,0,0,0,0,0,0,NaN
8,1738368009052000000,0,0,0,0,0,0,NaN
9,1738368010052000000,0,0,0,0,0,0,NaN
10,1738368011052000000,0,0,0,0,0,0,NaN
11,1738368012052000000,0,0,0,0,0,0,NaN
12,1738368013052000000,0,0,0,0,0,0,NaN
13,1738368014052000000,0,0,0,0,0,0,NaN
14,1738368015052000000,0,0,0,0,0,0,NaN
15,1738368016052000000,0,0,0,0,0,0,NaN
16,1738368017052000000,0,0,0,0,0,0,NaN
17,1738368018052000000,0,0,0,0,0,0,NaN
18,1738368019052000000,0,0,0,0,0,0,NaN
19,1738368020052000000,0,0,0,0,0,0,NaN

In [78]:
import numpy as np
data = np.load("/data/tmp/tardis_bn_hft/data/binance-futures/SOLUSDT/SOLUSDT_20250131_EOD.npz")
df = data['data']
print(df.shape)

(12645,)

In [79]:
df = data['data'][-400:]
print(df)

[(3489660932, 0, 0,  325.65, 7.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  325.84, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  325.85, 2.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  325.91, 2.7000e+01, 0, 0, 0.)
 (3489660932, 0, 0,  325.92, 4.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  326.13, 2.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  326.15, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  326.23, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  326.37, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  326.4 , 3.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  326.44, 2.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  326.57, 2.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  326.68, 2.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  326.69, 3.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  326.74, 2.6000e+01, 0, 0, 0.)
 (3489660932, 0, 0,  326.85, 7.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  326.86, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  326.91, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  326.92, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  327.23, 2.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  327.33, 3.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  327.46, 3.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  327.51, 2.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  327.57, 2.7000e+01, 0, 0, 0.)
 (3489660932, 0, 0,  327.62, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  327.65, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  327.69, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  328.  , 2.8000e+01, 0, 0, 0.)
 (3489660932, 0, 0,  328.04, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  328.05, 2.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  328.16, 5.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  328.22, 2.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  328.23, 5.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  328.34, 2.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  328.4 , 2.6000e+01, 0, 0, 0.)
 (3489660932, 0, 0,  328.46, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  328.63, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  328.67, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  329.  , 2.8000e+01, 0, 0, 0.)
 (3489660932, 0, 0,  329.11, 2.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  329.17, 3.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  329.23, 2.7000e+01, 0, 0, 0.)
 (3489660932, 0, 0,  329.34, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  329.45, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  329.56, 2.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  329.7 , 2.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  330.  , 1.1449e+04, 0, 0, 0.)
 (3489660932, 0, 0,  330.05, 2.6000e+01, 0, 0, 0.)
 (3489660932, 0, 0,  330.17, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  330.35, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  330.41, 2.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  330.52, 2.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  330.56, 2.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  330.76, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  330.88, 2.9000e+01, 0, 0, 0.)
 (3489660932, 0, 0,  331.  , 3.4000e+01, 0, 0, 0.)
 (3489660932, 0, 0,  331.06, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  331.37, 2.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  331.42, 2.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  331.5 , 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  331.53, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  331.56, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  331.63, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  331.71, 2.6000e+01, 0, 0, 0.)
 (3489660932, 0, 0,  331.78, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  332.  , 7.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  332.05, 5.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  332.3 , 2.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  332.54, 2.6000e+01, 0, 0, 0.)
 (3489660932, 0, 0,  332.71, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  332.88, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  332.89, 7.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  333.  , 3.6000e+01, 0, 0, 0.)
 (3489660932, 0, 0,  333.01, 3.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  333.07, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  333.33, 4.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  333.37, 2.6000e+01, 0, 0, 0.)
 (3489660932, 0, 0,  333.55, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  333.69, 3.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  333.84, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  333.85, 2.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  333.88, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  333.9 , 2.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  334.2 , 2.6000e+01, 0, 0, 0.)
 (3489660932, 0, 0,  334.22, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  334.32, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  334.5 , 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  334.61, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  334.85, 2.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  335.  , 6.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  335.02, 2.6000e+01, 0, 0, 0.)
 (3489660932, 0, 0,  335.14, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  335.38, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  335.54, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  335.55, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  335.68, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  335.75, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  335.85, 2.7000e+01, 0, 0, 0.)
 (3489660932, 0, 0,  335.95, 1.2000e+01, 0, 0, 0.)
 (3489660932, 0, 0,  336.  , 1.8000e+01, 0, 0, 0.)
 (3489660932, 0, 0,  336.15, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  336.66, 2.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  336.68, 2.6000e+01, 0, 0, 0.)
 (3489660932, 0, 0,  336.92, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  336.97, 6.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  337.  , 6.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  337.33, 2.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  337.42, 2.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  337.51, 2.6000e+01, 0, 0, 0.)
 (3489660932, 0, 0,  337.54, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  337.69, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  337.92, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  337.94, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  338.  , 1.5700e+02, 0, 0, 0.)
 (3489660932, 0, 0,  338.26, 2.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  338.3 , 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  338.34, 2.6000e+01, 0, 0, 0.)
 (3489660932, 0, 0,  338.46, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  339.  , 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  339.1 , 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  339.17, 2.6000e+01, 0, 0, 0.)
 (3489660932, 0, 0,  339.23, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  339.54, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  339.85, 5.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  339.86, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  339.87, 1.0000e+02, 0, 0, 0.)
 (3489660932, 0, 0,  340.  , 2.8900e+02, 0, 0, 0.)
 (3489660932, 0, 0,  340.07, 1.0000e+01, 0, 0, 0.)
 (3489660932, 0, 0,  340.11, 2.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  340.37, 2.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  340.38, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  340.41, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  340.51, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  340.75, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  340.76, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  341.  , 3.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  341.2 , 2.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  341.33, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  341.38, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  341.53, 4.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  341.85, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  342.  , 2.0000e+01, 0, 0, 0.)
 (3489660932, 0, 0,  342.04, 2.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  342.27, 1.9000e+01, 0, 0, 0.)
 (3489660932, 0, 0,  342.3 , 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  342.48, 3.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  343.07, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  343.33, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  343.43, 2.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  343.53, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  343.55, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  343.74, 5.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  343.84, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  343.97, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  344.  , 3.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  344.04, 1.0000e+02, 0, 0, 0.)
 (3489660932, 0, 0,  344.44, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  344.61, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  344.62, 2.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  344.82, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  345.  , 1.2900e+02, 0, 0, 0.)
 (3489660932, 0, 0,  345.08, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  345.3 , 3.3060e+03, 0, 0, 0.)
 (3489660932, 0, 0,  345.38, 2.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  345.52, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  345.68, 4.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  346.15, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  346.25, 3.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  346.26, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  346.41, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  346.66, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  346.92, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  347.  , 6.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  347.11, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  347.52, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  347.55, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  347.64, 5.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  347.69, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  347.75, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  348.  , 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  348.26, 2.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  348.4 , 2.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  348.46, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  348.85, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  349.  , 4.0000e+01, 0, 0, 0.)
 (3489660932, 0, 0,  349.23, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  349.51, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  350.  , 2.0120e+03, 0, 0, 0.)
 (3489660932, 0, 0,  350.05, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  350.22, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  350.78, 3.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  350.8 , 1.9000e+01, 0, 0, 0.)
 (3489660932, 0, 0,  351.  , 8.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  351.28, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  351.51, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  351.54, 5.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  351.64, 7.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  351.7 , 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  352.  , 3.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  353.5 , 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  353.66, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  353.72, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  354.2 , 2.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  355.02, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  355.14, 1.7000e+01, 0, 0, 0.)
 (3489660932, 0, 0,  355.44, 5.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  355.5 , 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  356.  , 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  356.16, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  356.6 , 1.6000e+01, 0, 0, 0.)
 (3489660932, 0, 0,  357.  , 3.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  358.17, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  358.58, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  358.6 , 2.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  359.2 , 2.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  359.28, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  359.33, 5.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  360.  , 1.4300e+02, 0, 0, 0.)
 (3489660932, 0, 0,  360.66, 4.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  361.04, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  362.02, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  362.15, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  362.72, 2.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  363.  , 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  363.23, 5.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  363.47, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  364.  , 3.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  364.23, 1.0000e+03, 0, 0, 0.)
 (3489660932, 0, 0,  364.49, 2.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  365.  , 2.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  365.46, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  365.91, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  366.  , 4.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  366.12, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  366.98, 1.6000e+01, 0, 0, 0.)
 (3489660932, 0, 0,  367.13, 5.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  368.  , 5.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  368.35, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  368.9 , 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  369.64, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  370.  , 7.4700e+02, 0, 0, 0.)
 (3489660932, 0, 0,  370.1 , 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  370.79, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  371.02, 5.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  372.  , 2.8000e+01, 0, 0, 0.)
 (3489660932, 0, 0,  372.34, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  373.23, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  373.84, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  374.07, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  374.92, 5.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  375.  , 7.2100e+02, 0, 0, 0.)
 (3489660932, 0, 0,  375.66, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  375.78, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  376.  , 1.8000e+01, 0, 0, 0.)
 (3489660932, 0, 0,  377.  , 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  378.05, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  378.1 , 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  378.82, 5.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  379.  , 7.7000e+01, 0, 0, 0.)
 (3489660932, 0, 0,  379.22, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  379.81, 3.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  380.  , 7.4500e+02, 0, 0, 0.)
 (3489660932, 0, 0,  380.54, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  382.02, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  382.66, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  382.72, 5.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  382.98, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  383.  , 8.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  384.  , 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  384.26, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  385.42, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  385.6 , 2.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  386.  , 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  386.1 , 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  386.61, 5.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  387.  , 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  387.85, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  388.  , 1.3000e+01, 0, 0, 0.)
 (3489660932, 0, 0,  388.88, 1.2930e+03, 0, 0, 0.)
 (3489660932, 0, 0,  389.54, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  390.  , 1.4000e+02, 0, 0, 0.)
 (3489660932, 0, 0,  390.29, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  390.51, 5.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  392.  , 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  392.73, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  392.98, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  394.41, 5.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  395.  , 1.3000e+01, 0, 0, 0.)
 (3489660932, 0, 0,  395.17, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  396.  , 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  396.42, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  397.6 , 3.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  398.1 , 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  398.31, 5.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  398.87, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  399.81, 3.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  400.  , 1.3900e+02, 0, 0, 0.)
 (3489660932, 0, 0,  400.04, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  402.48, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  404.  , 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  404.92, 2.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  407.36, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  408.  , 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  409.79, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  412.  , 6.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  412.23, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  414.67, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  416.  , 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  417.11, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  419.55, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  420.  , 2.7000e+02, 0, 0, 0.)
 (3489660932, 0, 0,  421.98, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  424.  , 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  424.42, 3.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  426.33, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  426.86, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  428.  , 3.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  429.3 , 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  430.  , 5.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  431.73, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  432.  , 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  433.33, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  433.64, 2.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  434.17, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  436.  , 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  436.61, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  439.05, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  439.81, 3.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  440.  , 2.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  441.49, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  443.92, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  444.  , 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  446.36, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  448.  , 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  448.8 , 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  450.  , 1.6600e+02, 0, 0, 0.)
 (3489660932, 0, 0,  451.24, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  452.  , 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  452.6 , 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  453.36, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  453.68, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  456.  , 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  456.11, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  456.3 , 2.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  458.55, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  458.56, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  460.  , 2.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  460.99, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  463.43, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  464.  , 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  465.86, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  468.  , 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  468.3 , 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  470.74, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  472.  , 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  473.18, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  474.  , 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  474.03, 5.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  474.43, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  474.46, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  475.62, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  476.  , 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  477.2 , 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  477.61, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  478.05, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  479.93, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  480.  , 9.7600e+02, 0, 0, 0.)
 (3489660932, 0, 0,  480.49, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  481.53, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  482.24, 6.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  482.93, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  485.37, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  487.81, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  488.  , 8.3000e+01, 0, 0, 0.)
 (3489660932, 0, 0,  488.88, 5.0000e+02, 0, 0, 0.)
 (3489660932, 0, 0,  489.81, 3.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  490.24, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  492.68, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  494.  , 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  495.12, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  497.56, 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  500.  , 8.4400e+02, 0, 0, 0.)
 (3489660932, 0, 0,  510.  , 1.6600e+02, 0, 0, 0.)
 (3489660932, 0, 0,  520.  , 1.2220e+03, 0, 0, 0.)
 (3489660932, 0, 0,  530.  , 1.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  540.  , 1.0000e+02, 0, 0, 0.)
 (3489660932, 0, 0,  541.  , 4.0000e+00, 0, 0, 0.)
 (3489660932, 0, 0,  568.88, 5.0000e+02, 0, 0, 0.)
 (3489660932, 0, 0,  588.  , 1.0000e+01, 0, 0, 0.)
 (3489660932, 0, 0,  589.  , 2.3400e+03, 0, 0, 0.)
 (3489660932, 0, 0,  600.  , 1.2700e+02, 0, 0, 0.)
 (3489660932, 0, 0,  620.  , 1.0000e+02, 0, 0, 0.)

In [75]:
import numpy as np
data = np.load("/data/tmp/tardis_bn_hft/data/binance-futures/SOLUSDT/SOLUSDT_20250130.npz")
df = data['data'][-200:]
print(df)

[(3489660929, 1738281599685000000, 1738281599688592000, 238.19, 2.1400e+02, 0, 0, 0.)
 (3489660929, 1738281599685000000, 1738281599688592000, 238.29, 3.6800e+02, 0, 0, 0.)
 (3489660929, 1738281599685000000, 1738281599688592000, 238.96, 1.9100e+02, 0, 0, 0.)
 (3489660929, 1738281599685000000, 1738281599688592000, 238.98, 9.9000e+01, 0, 0, 0.)
 (3489660929, 1738281599685000000, 1738281599688592000, 239.  , 6.9000e+01, 0, 0, 0.)
 (3489660929, 1738281599685000000, 1738281599688592000, 240.51, 4.7000e+01, 0, 0, 0.)
 (3758096385, 1738281599685000000, 1738281599688592000, 236.22, 3.0000e+00, 0, 0, 0.)
 (3758096385, 1738281599685000000, 1738281599688592000, 236.46, 1.5500e+02, 0, 0, 0.)
 (3758096385, 1738281599685000000, 1738281599688592000, 236.7 , 2.7400e+02, 0, 0, 0.)
 (3758096385, 1738281599685000000, 1738281599688592000, 236.77, 2.4600e+02, 0, 0, 0.)
 (3758096385, 1738281599685000000, 1738281599688592000, 237.06, 4.2100e+02, 0, 0, 0.)
 (3758096385, 1738281599685000000, 1738281599688592000, 237.08, 2.7200e+02, 0, 0, 0.)
 (3758096385, 1738281599685000000, 1738281599688592000, 237.1 , 1.2300e+02, 0, 0, 0.)
 (3758096385, 1738281599685000000, 1738281599688592000, 237.13, 4.5200e+02, 0, 0, 0.)
 (3758096385, 1738281599685000000, 1738281599688592000, 237.15, 2.6600e+02, 0, 0, 0.)
 (3758096385, 1738281599685000000, 1738281599688592000, 237.17, 1.3000e+02, 0, 0, 0.)
 (3758096385, 1738281599685000000, 1738281599688592000, 237.2 , 4.8700e+02, 0, 0, 0.)
 (3758096385, 1738281599685000000, 1738281599688592000, 237.93, 4.2500e+02, 0, 0, 0.)
 (3758096385, 1738281599685000000, 1738281599688592000, 237.97, 5.0600e+02, 0, 0, 0.)
 (3758096385, 1738281599685000000, 1738281599688592000, 237.98, 3.2800e+02, 0, 0, 0.)
 (3758096385, 1738281599685000000, 1738281599688592000, 238.07, 1.0900e+02, 0, 0, 0.)
 (3758096385, 1738281599685000000, 1738281599688592000, 238.09, 2.2700e+02, 0, 0, 0.)
 (3758096385, 1738281599685000000, 1738281599688592000, 238.11, 7.5000e+01, 0, 0, 0.)
 (3758096385, 1738281599685000000, 1738281599688592000, 238.12, 1.2700e+02, 0, 0, 0.)
 (3489660929, 1738281599736000000, 1738281599738765000, 238.14, 6.0000e+00, 0, 0, 0.)
 (3489660929, 1738281599736000000, 1738281599738765000, 238.22, 8.6200e+02, 0, 0, 0.)
 (3489660929, 1738281599736000000, 1738281599738765000, 238.27, 1.0100e+02, 0, 0, 0.)
 (3489660929, 1738281599736000000, 1738281599738765000, 238.29, 3.7100e+02, 0, 0, 0.)
 (3489660929, 1738281599736000000, 1738281599738765000, 238.3 , 2.2500e+02, 0, 0, 0.)
 (3489660929, 1738281599736000000, 1738281599738765000, 238.36, 2.8100e+02, 0, 0, 0.)
 (3489660929, 1738281599736000000, 1738281599738765000, 239.12, 1.2100e+02, 0, 0, 0.)
 (3489660929, 1738281599736000000, 1738281599738765000, 240.51, 4.7000e+01, 0, 0, 0.)
 (3489660929, 1738281599736000000, 1738281599738765000, 240.69, 3.0000e+00, 0, 0, 0.)
 (3489660929, 1738281599736000000, 1738281599738765000, 240.7 , 2.4000e+01, 0, 0, 0.)
 (3758096385, 1738281599736000000, 1738281599738765000, 119.1 , 1.0000e+00, 0, 0, 0.)
 (3758096385, 1738281599736000000, 1738281599738765000, 235.74, 1.0000e+01, 0, 0, 0.)
 (3758096385, 1738281599736000000, 1738281599738765000, 237.41, 2.6600e+02, 0, 0, 0.)
 (3758096385, 1738281599736000000, 1738281599738765000, 237.79, 2.5300e+02, 0, 0, 0.)
 (3758096385, 1738281599736000000, 1738281599738765000, 238.08, 2.5400e+02, 0, 0, 0.)
 (3758096385, 1738281599736000000, 1738281599738765000, 238.1 , 1.7800e+02, 0, 0, 0.)
 (3758096385, 1738281599736000000, 1738281599738765000, 238.12, 1.2800e+02, 0, 0, 0.)
 (3489660929, 1738281599788000000, 1738281599790826000, 238.17, 2.1700e+02, 0, 0, 0.)
 (3489660929, 1738281599788000000, 1738281599790826000, 240.51, 4.7000e+01, 0, 0, 0.)
 (3489660929, 1738281599788000000, 1738281599790826000, 259.55, 1.0000e+01, 0, 0, 0.)
 (3489660929, 1738281599841000000, 1738281599844625000, 238.16, 8.3000e+01, 0, 0, 0.)
 (3489660929, 1738281599841000000, 1738281599844625000, 238.17, 2.4800e+02, 0, 0, 0.)
 (3489660929, 1738281599841000000, 1738281599844625000, 238.67, 3.2900e+02, 0, 0, 0.)
 (3489660929, 1738281599841000000, 1738281599844625000, 238.68, 1.4900e+02, 0, 0, 0.)
 (3489660929, 1738281599841000000, 1738281599844625000, 239.36, 9.9500e+02, 0, 0, 0.)
 (3489660929, 1738281599841000000, 1738281599844625000, 239.88, 2.1240e+03, 0, 0, 0.)
 (3489660929, 1738281599841000000, 1738281599844625000, 241.07, 5.8300e+02, 0, 0, 0.)
 (3489660929, 1738281599841000000, 1738281599844625000, 241.67, 2.4970e+03, 0, 0, 0.)
 (3489660929, 1738281599841000000, 1738281599844625000, 242.19, 8.5000e+02, 0, 0, 0.)
 (3489660929, 1738281599841000000, 1738281599844625000, 259.55, 3.0000e+00, 0, 0, 0.)
 (3758096385, 1738281599841000000, 1738281599844625000, 234.08, 6.0100e+02, 0, 0, 0.)
 (3758096385, 1738281599841000000, 1738281599844625000, 234.2 , 1.3910e+03, 0, 0, 0.)
 (3758096385, 1738281599841000000, 1738281599844625000, 234.6 , 1.5550e+03, 0, 0, 0.)
 (3758096385, 1738281599841000000, 1738281599844625000, 234.72, 1.6020e+03, 0, 0, 0.)
 (3758096385, 1738281599841000000, 1738281599844625000, 235.19, 4.3600e+02, 0, 0, 0.)
 (3758096385, 1738281599841000000, 1738281599844625000, 235.32, 5.8200e+02, 0, 0, 0.)
 (3758096385, 1738281599841000000, 1738281599844625000, 236.49, 5.3000e+01, 0, 0, 0.)
 (3758096385, 1738281599841000000, 1738281599844625000, 236.67, 8.2000e+01, 0, 0, 0.)
 (3758096385, 1738281599841000000, 1738281599844625000, 237.01, 9.7700e+02, 0, 0, 0.)
 (3758096385, 1738281599841000000, 1738281599844625000, 237.19, 1.0200e+02, 0, 0, 0.)
 (3758096385, 1738281599841000000, 1738281599844625000, 237.33, 2.6000e+02, 0, 0, 0.)
 (3758096385, 1738281599841000000, 1738281599844625000, 237.6 , 4.8300e+02, 0, 0, 0.)
 (3758096385, 1738281599841000000, 1738281599844625000, 237.7 , 2.6900e+02, 0, 0, 0.)
 (3758096385, 1738281599841000000, 1738281599844625000, 237.79, 2.5400e+02, 0, 0, 0.)
 (3758096385, 1738281599841000000, 1738281599844625000, 238.07, 2.6200e+02, 0, 0, 0.)
 (3758096385, 1738281599841000000, 1738281599844625000, 238.08, 1.0100e+02, 0, 0, 0.)
 (3489660929, 1738281599893000000, 1738281599897136000, 238.13, 1.1200e+02, 0, 0, 0.)
 (3489660929, 1738281599893000000, 1738281599897136000, 238.15, 5.0000e+01, 0, 0, 0.)
 (3489660929, 1738281599893000000, 1738281599897136000, 238.16, 9.0000e+00, 0, 0, 0.)
 (3489660929, 1738281599893000000, 1738281599897136000, 238.17, 1.3500e+02, 0, 0, 0.)
 (3489660929, 1738281599893000000, 1738281599897136000, 238.18, 1.4800e+02, 0, 0, 0.)
 (3489660929, 1738281599893000000, 1738281599897136000, 238.19, 1.7200e+02, 0, 0, 0.)
 (3489660929, 1738281599893000000, 1738281599897136000, 238.2 , 8.0300e+02, 0, 0, 0.)
 (3489660929, 1738281599893000000, 1738281599897136000, 238.22, 9.0300e+02, 0, 0, 0.)
 (3489660929, 1738281599893000000, 1738281599897136000, 238.23, 3.2300e+02, 0, 0, 0.)
 (3489660929, 1738281599893000000, 1738281599897136000, 238.24, 4.3500e+02, 0, 0, 0.)
 (3489660929, 1738281599893000000, 1738281599897136000, 238.35, 4.1600e+02, 0, 0, 0.)
 (3489660929, 1738281599893000000, 1738281599897136000, 238.38, 2.7400e+02, 0, 0, 0.)
 (3489660929, 1738281599893000000, 1738281599897136000, 238.69, 7.9300e+02, 0, 0, 0.)
 (3489660929, 1738281599893000000, 1738281599897136000, 238.86, 1.6600e+02, 0, 0, 0.)
 (3489660929, 1738281599893000000, 1738281599897136000, 238.87, 2.2300e+02, 0, 0, 0.)
 (3489660929, 1738281599893000000, 1738281599897136000, 238.89, 2.4100e+02, 0, 0, 0.)
 (3489660929, 1738281599893000000, 1738281599897136000, 239.29, 9.5500e+02, 0, 0, 0.)
 (3489660929, 1738281599893000000, 1738281599897136000, 239.35, 3.1900e+02, 0, 0, 0.)
 (3489660929, 1738281599893000000, 1738281599897136000, 239.81, 8.3000e+02, 0, 0, 0.)
 (3489660929, 1738281599893000000, 1738281599897136000, 239.86, 3.1900e+02, 0, 0, 0.)
 (3489660929, 1738281599893000000, 1738281599897136000, 241.07, 3.6000e+01, 0, 0, 0.)
 (3489660929, 1738281599893000000, 1738281599897136000, 241.67, 1.6770e+03, 0, 0, 0.)
 (3489660929, 1738281599893000000, 1738281599897136000, 242.19, 3.0000e+01, 0, 0, 0.)
 (3489660929, 1738281599893000000, 1738281599897136000, 246.78, 2.2000e+01, 0, 0, 0.)
 (3489660929, 1738281599893000000, 1738281599897136000, 246.9 , 1.0000e+00, 0, 0, 0.)
 (3758096385, 1738281599893000000, 1738281599897136000, 234.08, 1.5000e+01, 0, 0, 0.)
 (3758096385, 1738281599893000000, 1738281599897136000, 234.2 , 5.7100e+02, 0, 0, 0.)
 (3758096385, 1738281599893000000, 1738281599897136000, 234.6 , 9.6900e+02, 0, 0, 0.)
 (3758096385, 1738281599893000000, 1738281599897136000, 234.72, 7.8200e+02, 0, 0, 0.)
 (3758096385, 1738281599893000000, 1738281599897136000, 235.19, 4.5000e+01, 0, 0, 0.)
 (3758096385, 1738281599893000000, 1738281599897136000, 235.32, 3.5000e+01, 0, 0, 0.)
 (3758096385, 1738281599893000000, 1738281599897136000, 236.46, 7.4100e+02, 0, 0, 0.)
 (3758096385, 1738281599893000000, 1738281599897136000, 236.5 , 4.0000e+02, 0, 0, 0.)
 (3758096385, 1738281599893000000, 1738281599897136000, 236.58, 1.9170e+03, 0, 0, 0.)
 (3758096385, 1738281599893000000, 1738281599897136000, 236.67, 3.9000e+01, 0, 0, 0.)
 (3758096385, 1738281599893000000, 1738281599897136000, 236.68, 6.0000e+01, 0, 0, 0.)
 (3758096385, 1738281599893000000, 1738281599897136000, 236.98, 7.3000e+02, 0, 0, 0.)
 (3758096385, 1738281599893000000, 1738281599897136000, 237.02, 1.7200e+02, 0, 0, 0.)
 (3758096385, 1738281599893000000, 1738281599897136000, 237.1 , 9.4300e+02, 0, 0, 0.)
 (3758096385, 1738281599893000000, 1738281599897136000, 237.2 , 3.0200e+02, 0, 0, 0.)
 (3758096385, 1738281599893000000, 1738281599897136000, 237.57, 7.3400e+02, 0, 0, 0.)
 (3758096385, 1738281599893000000, 1738281599897136000, 237.61, 2.2100e+02, 0, 0, 0.)
 (3758096385, 1738281599893000000, 1738281599897136000, 237.7 , 8.1600e+02, 0, 0, 0.)
 (3758096385, 1738281599893000000, 1738281599897136000, 237.71, 1.7100e+02, 0, 0, 0.)
 (3758096385, 1738281599893000000, 1738281599897136000, 237.72, 4.5200e+02, 0, 0, 0.)
 (3758096385, 1738281599893000000, 1738281599897136000, 237.85, 4.1300e+02, 0, 0, 0.)
 (3758096385, 1738281599893000000, 1738281599897136000, 237.87, 5.0000e+02, 0, 0, 0.)
 (3758096385, 1738281599893000000, 1738281599897136000, 237.89, 2.3100e+02, 0, 0, 0.)
 (3758096385, 1738281599893000000, 1738281599897136000, 237.91, 3.5300e+02, 0, 0, 0.)
 (3758096385, 1738281599893000000, 1738281599897136000, 237.93, 4.6800e+02, 0, 0, 0.)
 (3758096385, 1738281599893000000, 1738281599897136000, 237.94, 1.8300e+02, 0, 0, 0.)
 (3758096385, 1738281599893000000, 1738281599897136000, 237.98, 3.5900e+02, 0, 0, 0.)
 (3758096385, 1738281599893000000, 1738281599897136000, 238.07, 1.0900e+02, 0, 0, 0.)
 (3758096385, 1738281599893000000, 1738281599897136000, 238.08, 1.2600e+02, 0, 0, 0.)
 (3758096385, 1738281599893000000, 1738281599897136000, 238.09, 2.0000e+02, 0, 0, 0.)
 (3758096385, 1738281599893000000, 1738281599897136000, 238.1 , 3.3100e+02, 0, 0, 0.)
 (3758096385, 1738281599893000000, 1738281599897136000, 238.12, 1.4200e+02, 0, 0, 0.)
 (3758096386, 1738281599933000000, 1738281599936303000, 238.13, 1.0000e+01, 0, 0, 0.)
 (3758096386, 1738281599934000000, 1738281599937350000, 238.13, 8.0000e+00, 0, 0, 0.)
 (3758096386, 1738281599934000000, 1738281599937352000, 238.13, 4.9000e+01, 0, 0, 0.)
 (3758096386, 1738281599934000000, 1738281599937357000, 238.13, 4.4000e+01, 0, 0, 0.)
 (3758096386, 1738281599934000000, 1738281599937358000, 238.13, 1.0000e+00, 0, 0, 0.)
 (3758096386, 1738281599936000000, 1738281599939522000, 238.14, 1.0000e+00, 0, 0, 0.)
 (3758096386, 1738281599936000000, 1738281599939528000, 238.14, 1.0000e+00, 0, 0, 0.)
 (3758096386, 1738281599936000000, 1738281599939530000, 238.14, 1.0000e+00, 0, 0, 0.)
 (3758096386, 1738281599943000000, 1738281599946650000, 238.15, 2.0000e+00, 0, 0, 0.)
 (3489660929, 1738281599947000000, 1738281599949761000, 238.13, 0.0000e+00, 0, 0, 0.)
 (3489660929, 1738281599947000000, 1738281599949761000, 238.14, 0.0000e+00, 0, 0, 0.)
 (3489660929, 1738281599947000000, 1738281599949761000, 238.15, 2.5000e+01, 0, 0, 0.)
 (3489660929, 1738281599947000000, 1738281599949761000, 238.16, 4.0000e+00, 0, 0, 0.)
 (3489660929, 1738281599947000000, 1738281599949761000, 238.17, 4.9000e+01, 0, 0, 0.)
 (3489660929, 1738281599947000000, 1738281599949761000, 238.18, 1.3200e+02, 0, 0, 0.)
 (3489660929, 1738281599947000000, 1738281599949761000, 238.19, 2.5500e+02, 0, 0, 0.)
 (3489660929, 1738281599947000000, 1738281599949761000, 238.2 , 6.8900e+02, 0, 0, 0.)
 (3489660929, 1738281599947000000, 1738281599949761000, 238.21, 7.4200e+02, 0, 0, 0.)
 (3489660929, 1738281599947000000, 1738281599949761000, 238.22, 8.2700e+02, 0, 0, 0.)
 (3489660929, 1738281599947000000, 1738281599949761000, 238.23, 3.2600e+02, 0, 0, 0.)
 (3489660929, 1738281599947000000, 1738281599949761000, 238.24, 4.3600e+02, 0, 0, 0.)
 (3489660929, 1738281599947000000, 1738281599949761000, 238.25, 2.3600e+02, 0, 0, 0.)
 (3489660929, 1738281599947000000, 1738281599949761000, 238.26, 5.2200e+02, 0, 0, 0.)
 (3489660929, 1738281599947000000, 1738281599949761000, 238.28, 3.1800e+02, 0, 0, 0.)
 (3489660929, 1738281599947000000, 1738281599949761000, 238.42, 1.5900e+02, 0, 0, 0.)
 (3489660929, 1738281599947000000, 1738281599949761000, 238.86, 1.7300e+02, 0, 0, 0.)
 (3489660929, 1738281599947000000, 1738281599949761000, 238.87, 1.4400e+02, 0, 0, 0.)
 (3489660929, 1738281599947000000, 1738281599949761000, 238.88, 2.7400e+02, 0, 0, 0.)
 (3489660929, 1738281599947000000, 1738281599949761000, 238.9 , 7.2300e+02, 0, 0, 0.)
 (3489660929, 1738281599947000000, 1738281599949761000, 239.28, 2.5200e+02, 0, 0, 0.)
 (3489660929, 1738281599947000000, 1738281599949761000, 239.34, 5.4000e+01, 0, 0, 0.)
 (3489660929, 1738281599947000000, 1738281599949761000, 239.35, 3.0300e+02, 0, 0, 0.)
 (3489660929, 1738281599947000000, 1738281599949761000, 239.8 , 1.3700e+02, 0, 0, 0.)
 (3489660929, 1738281599947000000, 1738281599949761000, 239.86, 3.3500e+02, 0, 0, 0.)
 (3489660929, 1738281599947000000, 1738281599949761000, 240.51, 4.7000e+01, 0, 0, 0.)
 (3758096385, 1738281599947000000, 1738281599949761000, 234.06, 8.0000e+00, 0, 0, 0.)
 (3758096385, 1738281599947000000, 1738281599949761000, 235.74, 1.0000e+01, 0, 0, 0.)
 (3758096385, 1738281599947000000, 1738281599949761000, 236.47, 1.2180e+03, 0, 0, 0.)
 (3758096385, 1738281599947000000, 1738281599949761000, 236.51, 1.9600e+02, 0, 0, 0.)
 (3758096385, 1738281599947000000, 1738281599949761000, 236.59, 3.9500e+02, 0, 0, 0.)
 (3758096385, 1738281599947000000, 1738281599949761000, 236.69, 9.0000e+00, 0, 0, 0.)
 (3758096385, 1738281599947000000, 1738281599949761000, 236.99, 1.6200e+02, 0, 0, 0.)
 (3758096385, 1738281599947000000, 1738281599949761000, 237.11, 3.5600e+02, 0, 0, 0.)
 (3758096385, 1738281599947000000, 1738281599949761000, 237.35, 2.9700e+02, 0, 0, 0.)
 (3758096385, 1738281599947000000, 1738281599949761000, 237.58, 1.7300e+02, 0, 0, 0.)
 (3758096385, 1738281599947000000, 1738281599949761000, 237.62, 1.5400e+02, 0, 0, 0.)
 (3758096385, 1738281599947000000, 1738281599949761000, 237.71, 2.9400e+02, 0, 0, 0.)
 (3758096385, 1738281599947000000, 1738281599949761000, 237.77, 1.4500e+02, 0, 0, 0.)
 (3758096385, 1738281599947000000, 1738281599949761000, 237.81, 4.9600e+02, 0, 0, 0.)
 (3758096385, 1738281599947000000, 1738281599949761000, 237.88, 3.3700e+02, 0, 0, 0.)
 (3758096385, 1738281599947000000, 1738281599949761000, 237.89, 2.1000e+02, 0, 0, 0.)
 (3758096385, 1738281599947000000, 1738281599949761000, 237.9 , 5.6100e+02, 0, 0, 0.)
 (3758096385, 1738281599947000000, 1738281599949761000, 237.91, 3.5400e+02, 0, 0, 0.)
 (3758096385, 1738281599947000000, 1738281599949761000, 237.92, 5.6100e+02, 0, 0, 0.)
 (3758096385, 1738281599947000000, 1738281599949761000, 237.93, 4.8900e+02, 0, 0, 0.)
 (3758096385, 1738281599947000000, 1738281599949761000, 237.98, 3.6100e+02, 0, 0, 0.)
 (3758096385, 1738281599947000000, 1738281599949761000, 238.  , 2.8358e+04, 0, 0, 0.)
 (3758096385, 1738281599947000000, 1738281599949761000, 238.01, 6.1650e+03, 0, 0, 0.)
 (3758096385, 1738281599947000000, 1738281599949761000, 238.02, 5.0700e+02, 0, 0, 0.)
 (3758096385, 1738281599947000000, 1738281599949761000, 238.04, 1.6900e+02, 0, 0, 0.)
 (3758096385, 1738281599947000000, 1738281599949761000, 238.05, 2.0300e+02, 0, 0, 0.)
 (3758096385, 1738281599947000000, 1738281599949761000, 238.06, 2.1500e+02, 0, 0, 0.)
 (3758096385, 1738281599947000000, 1738281599949761000, 238.07, 8.9000e+01, 0, 0, 0.)
 (3758096385, 1738281599947000000, 1738281599949761000, 238.08, 1.2200e+02, 0, 0, 0.)
 (3758096385, 1738281599947000000, 1738281599949761000, 238.09, 2.1600e+02, 0, 0, 0.)
 (3758096385, 1738281599947000000, 1738281599949761000, 238.1 , 3.5000e+02, 0, 0, 0.)
 (3758096385, 1738281599947000000, 1738281599949761000, 238.11, 1.3600e+02, 0, 0, 0.)
 (3758096385, 1738281599947000000, 1738281599949761000, 238.12, 1.2400e+02, 0, 0, 0.)
 (3758096385, 1738281599947000000, 1738281599949761000, 238.13, 1.7300e+02, 0, 0, 0.)
 (3758096385, 1738281599947000000, 1738281599949761000, 238.14, 2.5000e+02, 0, 0, 0.)
 (3758096386, 1738281599967000000, 1738281599970578000, 238.15, 2.0000e+00, 0, 0, 0.)
 (3758096386, 1738281599967000000, 1738281599970584000, 238.15, 2.0000e+00, 0, 0, 0.)
 (3758096386, 1738281599967000000, 1738281599970584000, 238.15, 6.0000e+00, 0, 0, 0.)]

In [76]:
data['data'].dtype

dtype([('ev', '<u8'), ('exch_ts', '<i8'), ('local_ts', '<i8'), ('px', '<f8'), ('qty', '<f8'), ('order_id', '<u8'), ('ival', '<i8'), ('fval', '<f8')])

In [ ]:
import pandas as pd
pd.read_csv("/home/wtr2/statmm/out/SOLUSDT0.csv").tail(20)